server:
  port: 8182
  spring:  application:    name: convertcurrency-service 

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
