server:
  port: 8100
  
logging:
  level:
    org.springframework: ERROR
    com.ibm.taxservice: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  
spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
    
  zipkin:
    base-url: http://192.168.99.100:9411/
    
  sleuth:
    sampler:
      probability: 1.0
    trace-id128: true


          





