server:
  port: 8082
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
      
spring:  application:    name: order-service
    
  datasource:
    url: jdbc:h2:mem:Orderdb
    driver-class-name: org.h2.Driver
    username: ibm
    password: ibm
  h2:
    console:
      enabled: true
    